### ISSUE TITLE
Automatic resizing for smaller devices

### ISSUE THREAD

**Issue by jsilverMDX** [infinitered/redpotion#126]
Hi again guys.

I am having a problem making my app layout look good on some screens I made by hand on smaller devices. The app is designed for iPhone 6 and I am testing on iPod Touch 5g. Is there a recommended way of doing this? I'm not sure how to set up RMQ so that the views auto resize but it looked like this was supposed to happen by default. I would provide screen shots but they kind of give our app away.  The basic problem is that stuff is too big and it is leaking off the edge. Do I have to detect each screen size and provide sizes for each? That seems... tedious.

Anyway thanks again for a great library and I hope I'm not taking up too much of your guys time. Lol

**Comment by squidpunch** [comment]
It's hard to guess without some code. But here are some quick ideas that may help.  How are you setting the width of the view or the height?

I often use 'screen_width' which will be wider on the larger devices and smaller on the smaller. If you don't want the full width you can take some padding off etc

**Comment by jsilverMDX** [comment]
I am setting the t and l keys in the frame and the height and width. I will
try screen width. But what you're saying makes sense I think. Use the
screen width to calculate the values? Right now our designer is designing
for the other screens which might be over kill but will probably help me do
this properly.

**Comment by squidpunch** [comment]
so that means that no matter what device you are on you are going to go 47 points left and make a view 281 points wide
the iphone 4 and 5 are 320 points wide, 281 + 47 ends up being 328 points wide (8 points larger than the view you are working with)

Are you just trying to make a 47 margin on both sides? 281 + (47 * 2) = 375, the size of the 6

its worth mentioning that on the 6Plus this wouldnt be centered either, because we have 414 points to work with there.

assuming you are just trying to add 47 points padding to both sides, but then use the rest of the area to center the view....you could do something like this.

`st.frame = { t: 107, w: screen_width, padding: {l:47, r:47} }`

we have to send the full hash to padding because you dont want the same padding on top and bottom (I assume...)

you could do the math yourself too, if you prefer....
`st.frame = {t: 107, l: 47, w: screen_width - (47 * 2) }`

this should look the same on all devices

**Comment by jsilverMDX** [comment]
Thanks David. I will try this soon and let you know how it worked out for
me.

**Comment by skellock** [comment]
Same things as @squidpunch said, but "fr (from right)" works too:  `st.frame = {l: 47, fr: 47}' 

The only place I've had issues with this is on iPhone 6 & 6+ while inside a `UITableViewCell`.  And the work around for that is to style the cell & contentView explicitly with `{w: screen_width}`.  

Seems like an extra step (and it is), but will ensure the child controls you add to your `UITableViewCell` will have the proper `super_width`.   I've been meaning to dig into why, but I've been too swamped.  :non-potable_water:

**Comment by markrickert** [comment]
I know why. :)

UitableViewCells are created internally with a width of 320. We have no control over this. When they're laid out on the screen they're auto resized to the screen width. It's not a problem when the cell is reused. If we were using auto layout it would all just work. But since we're using explicit layouts when the cell is styled it think me its got a width of 320.

**Comment by squidpunch** [comment]
and yeah, steve's suggestion is yet another way, I always forget that you can just `l` and `fr` together like that!

@markrickert @skellock if its a custom cell you can get around that bug too by styling the content view

**Comment by twerth** [comment]
Yeah, :l and :fr is a good way to go. And yes you should always set the cell width to the screenwidth or the parent width. My 2-cents.

**Comment by jsilverMDX** [comment]
hey guys. thanks. this is working well.

i try similar stuff and it doesnt work with height. is there a recommendation on height?

**Comment by squidpunch** [comment]
the full screen height of the device in question is available as `screen_height` in the stylesheet.  Are you saying that you want a view that is different heights depending on the device? 

you can also set the height to `half` which would be half the screen size.  I dont think I've ever changed the height of views based on phone size, I usually go with more like a flow (add view, then below that view, and on an on - then the view is as big as it may need to be)

maybe an example of the problem would be easier to help you, if this doesnt match up?

**Comment by jsilverMDX** [comment]
Hi David,

Thanks for the response. I was not setting the actual height of any views
with screen height. What I did end up needing it for was some minor
differences between iPhone 5 and 6 in the "top" setting of some frames.
There may be a better way to do this like the one you just mentioned. But
for now this has worked.

If that sounds completely terrible, please stop me and I will consider
switching to the "this-below-that" style you mentioned :D

Thanks,
Jonathan

**Comment by squidpunch** [comment]
@jsilverMDX its not terrible, there is always more than one way to do something :)  If that works for you and you like the implementation then there is no harm.  You can definitely check device types and set tops based on different devices, it really depends on the layout you are rendering.  For me most of my screens start at the top, are X points tall, and then the next view goes below with a bit of a padding so that works for any screen size (though it could end up being empty on the bottom on something really long like an ipad or the iphone 6 - if it only had 2 views.  So I could totally see how you may want to space things differently or make them larger per device type - its all about the final effect you want to implement.  We here at RedPotion (and the included libraries we are choosing) try to make it easy and flexible to do what you want.  Glad you got it working!

**Comment by markrickert** [comment]
> We here at RedPotion...

You make it sound like we're all organized and responsible or something. lol

**Comment by squidpunch** [comment]
corporate life taking over lately, it bleeds over sometimes :hamster:

**Comment by jsilverMDX** [comment]
No worries guys. We had good success on this so far. Thanks everyone :) :+1:

**Comment by squidpunch** [comment]
@jsilvermdx glad to help!

**Comment by squidpunch** [comment]
@jsilvermdx glad to help!

**Comment by jsilverMDX** [comment]
Thanks
