### ISSUE TITLE
Generic screen template

### ISSUE THREAD

**Issue by twerth** [infinitered/redpotion#21]
@jamonholmgren and I talked about some new templates in RedPotion, one is a generic screen:

Basically we need a way to make any ol' controller a screen. API would be like this: 

`potion create generic_screen UICollectionViewController foos`

That would create that controller as a screen and include the `include ProMotion::ScreenModule` as well as some other included commented out. This way you can turn any controller type into a screen.

It should name this a **screen** and place it in the screens folder.

**Comment by jamonholmgren** [comment]
I think `potion create metal_screen foo` would work well, considering the `potion create metal_table_screen foo` precedent.

**Comment by andrewhavens** [comment]
I think that generating screens for custom view controllers is outside the scope of RedPotion. Generators are useful when several files are involved and boilerplate code is created. For a custom view controller, I only see this generator writing a few lines, and the generator would not be used often because the screens provided by ProMotion would be the default (used more often).

@twerth Do you still feel strongly about having this sort of generator? Or is this an issue we can close?
