### ISSUE TITLE
Require the cell template included in the model - DataTableScreen

### ISSUE THREAD

**Issue by squidpunch** [infinitered/redpotion#67]
Per a discussion we had on #64, I would like to propose that we enforce that the model is where the cell structure is defined.  It's cleaner, and more intention leading.  

@markrickert and I both agree that we prefer forcing the dev specify the cell be in the model.  We should probably include that the cell method is implemented on the model and raise an error if not if we are going to be forcing that the cell is defined in the model used for the screen.

I am interested in others thoughts, agree? disagree?  Dont care?  Chime in now!

**Comment by squidpunch** [comment]
If we have consensus, I might be able to swing some time to work on this one evening, or I am sure @markrickert can bang it out quickly as well (or maybe we should find some time and pair!)

**Comment by jamonholmgren** [comment]
I like this idea.

**Comment by markrickert** [comment]
We have a consensus! lol :D

**Comment by twerth** [comment]
To clarify, you mean if you user a ProMotion table screen only, correct?

**Comment by jamonholmgren** [comment]
`DataTableScreen`, I believe.

**Comment by twerth** [comment]
Ah, then sure. I don't like the actual view cell class in there, as it seems dirty, but I'm not partial either way.

**Comment by squidpunch** [comment]
@twerth you dont like the view cell class in the `DataTableScreen`, or you dont like it in the model that is represented on that screen?

It's definitely a messy implementation on the `DataTableScreen` directly as it is today because I just whipped something together to get a sort of proof of concept working and we could iron out the kinks.

I think we're all on board - I will see if I can slot some time and work on it - unless you want to run with it @markrickert

**Comment by dchersey** [comment]
This addition to ProMotion is great! The only thing that is messing me right up right now is the decision  to put the cell definition on the Model :(  My choice of custom cells depends on aspects of the View! I cannot have the same custom cell for each row.  

I am considering a PR to keep the current behavior by default, but allow the view to implement cell_for or some such which if present will allow the view to supply the cell definition on a per-model-instance basis. 

Any thoughts? Has this already been hashed out elsewhere?

**Comment by jamonholmgren** [comment]
@dchersey Thanks for the question! Ultimately, it's up to the community going forward. Most of us ProMotion users from 2015 are now on React Native and don't use RubyMotion anymore. So, there are still 31 "watchers" on this repo -- what do you think?

**Comment by andrewhavens** [comment]
@dchersey I also ran into this when I was developing [`promotion-generators`](https://github.com/andrewhavens/redpotion-generators) I think the implementation of `DataTableScreen` is a little strange. In my scaffolding generator, I generate a normal `TableScreen` because the amount of code necessary to imitate it is not that much and it's easier to customize. Having the cell/view info defined in the model makes it difficult to work with and feels counter-intuitive to the MVC separation that we are used to. Personally, I'd prefer to deprecate the `DataTableScreen` and make it easier to generate table screens that are ready to use with CDQ, rather than continuing with an abstraction that makes it difficult to customize.

**Comment by dchersey** [comment]
Thanks @andrewhavens, I will check out the generator and see if it serves better!
